version: '3.7'

# 컴퓨터들
services:
  # 컴퓨터이름
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/ProjectJ-Backend/src
    ports:
      - '${SERVER_EXTERNAL_PORT}:${SERVER_INTERNAL_PORT}'
    env_file:
      - ./.env.docker

  # 컴퓨터이름
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DATABASE_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_EXTERNAL_PORT}:${DATABASE_INTERNAL_PORT}'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
